const Stub = () => null;
const MapView = Stub;
MapView.Animated = Stub;
export default MapView;
export const Marker = Stub;
export const Callout = Stub;
export const Polyline = Stub;
export const Polygon = Stub;
export const Circle = Stub;
export const Overlay = Stub;
export const PROVIDER_GOOGLE = null;
export const PROVIDER_DEFAULT = null;
export const MAP_TYPES = {};
export const UrlTile = Stub;
export const LocalTile = Stub;
export const Heatmap = Stub;
export const Geojson = Stub;
export const AnimatedRegion = class {};
